@startuml
start
:Ввод даты рождения D;
if (D % 2 == 0?) then (Да)
  :ROWS=5; COLS=4;
  :запрещены 2,8;
  :ищем минимальный;
else (Нет)
  :ROWS=4; COLS=5;
  :запрещены 3,7;
  :ищем максимальный;
endif

:Заполнение массива допустимыми числами;
:i = 0;
:j = 0;

repeat
  :Обновить min/max при необходимости;
  :i,j++;
repeat while (все элементы обработаны?)

:Вывод массива;
:Вывод найденного элемента и координат;
stop
@enduml
