@startuml
start
:Запуск программы;
:Ввод размера n (от 5 до 10);
:Создать массив n×n;
:Заполнить случайными числами;
:Вывести массив на форму (DataGridView);
:Вычислить сумму всех элементов;
:Вывести сумму на форму (Label);
stop
@enduml
